baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Phosphene.xyz'

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[params]
  description = "Software Development and Research"
  showPostsOnHomePage = "recent"
  avatarURL = "/humm.png"
  ShowBackToTopButton = true
  metaKeywords = ["blog", "gokarna", "hugo"] #seo
  accentColor = "#8000ff"
  footer = "Phosphene.xyz"
#  socialIcons = [
#    {name = "discord", url = "https://logodownload.org/wp-content/uploads/2017/11/discord-logo-01.png"}
#  ]


[menu]
  [[menu.main]]
    identifier = "posts"

    url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/dzyphr"
    weight = 4
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"

  [[menu.main]]
    identifier = "discord"
    name = "Discord"
    url = "https://discord.gg/nts97rGX"
    weight = 3

    # We use feather-icons: https://feathericons.com/
#   pre = "<span data-feather='github'></span>"
